### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by rbellens** [rodolfocop/oauth_client#2]
hi @rodolfocop 

I noticed you copied my `openid_client` package. Clearly, you are allowed to do so and I appreciate your intent to build upon my work. However, it seems you have removed the original license and copyright notice. This is of course not allowed. So, please correct this as soon as possible on both github and pub.dev.

I would also advise to use the fork functionality of git(hub) to copy a repo. This way, it is very traceable and transparent, what is the origin of the code and what is your contribution to it.

**Comment by rodolfocop** [comment]
Hello @rbellens, we made a copy of your project because we need a change that was going through more than 4 months without an update. As you have accepted our PR we will be canceling this project immediately. Thanks for everything.
